# Generated by Django 5.0.1 on 2024-02-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='image/')),
                ('role', models.CharField(max_length=30)),
                ('role_description', models.TextField()),
            ],
        ),
    ]
